volumes:
  pg_data:
    name: selftrading_pg_data
  caddy_data:
  caddy_config:
  ib_settings:

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  db:
    image: postgres:15
    container_name: trading-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-new_self_trading_db}
      APP_USER_PASSWORD: ${DB_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "max_connections=30"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "wal_buffers=8MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "tcp_keepalives_idle=60"
      - "-c"
      - "tcp_keepalives_interval=10"
      - "-c"
      - "tcp_keepalives_count=6"
      - "-c"
      - "log_min_duration_statement=1000"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "log_disconnections=on"
      - "-c"
      - "log_statement=ddl"
      - "-c"
      - "log_checkpoints=on"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "log_temp_files=0"
      - "-c"
      - "log_autovacuum_min_duration=0"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_rotation_size=100MB"
      - "-c"
      - "log_truncate_on_rotation=on"
      - "-c"
      - "restart_after_crash=on"
      - "-c"
      - "max_wal_size=1GB"
      - "-c"
      - "min_wal_size=80MB"
    mem_limit: 1g
    shm_size: 256m
    stop_grace_period: 60s
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/00-init-db.sql:ro
      - ./scripts/10-init-app-user.sh:/docker-entrypoint-initdb.d/10-init-app-user.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s


  db-init-tables:
    image: selftrading-api_gateway
    container_name: db-init-tables
    restart: "no"
    env_file: .env
    environment:
      DATABASE_URL_DOCKER: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DB_ALLOW_AUTO_CREATE_DB: "true"
      DB_ALLOW_AUTO_CREATE_TABLES: "true"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["python", "-m", "backend.database.init_db"]




  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_gateway
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - IB_GATEWAY_HOST=${IB_GATEWAY_HOST}
      - IB_GATEWAY_PORT=${IB_GATEWAY_PORT:-4004}
      - IB_CLIENT_ID_BASE=12000
      - IBKR_SNAPSHOT_TIMEOUT_SECONDS=5.0
      - IBKR_DELAYED_FALLBACK_SECONDS=2.5
      - QUOTE_CACHE_TTL=5
      - QUOTE_FETCH_CONCURRENCY=8
      - RUNNING_ENV=production
      - DB_ALLOW_AUTO_CREATE_DB=false
      - DB_ALLOW_AUTO_CREATE_TABLES=false
    depends_on:
      db:
        condition: service_healthy
      db-init-tables:
        condition: service_completed_successfully

  client-ui:
    build:
      context: .
      dockerfile: Dockerfile.client-ui-naive
    container_name: client-ui
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api_gateway

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: scheduler
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      db-init-tables:
        condition: service_completed_successfully
    environment:
      - IB_GATEWAY_HOST=${IB_GATEWAY_HOST}
      - IB_GATEWAY_PORT=${IB_GATEWAY_PORT:-4004}
      - IB_CLIENT_ID_BASE=12000
      - IBKR_SNAPSHOT_TIMEOUT_SECONDS=5.0
      - IBKR_DELAYED_FALLBACK_SECONDS=2.5
      - QUOTE_CACHE_TTL=5
      - QUOTE_FETCH_CONCURRENCY=8
      - RUNNING_ENV=production
      - DB_ALLOW_AUTO_CREATE_DB=false
      - DB_ALLOW_AUTO_CREATE_TABLES=false

  ib-gateway-1:
    container_name: ib-gateway-1
    image: ghcr.io/gnzsnz/ib-gateway:latest
    restart: always
    env_file:
      - .env
    shm_size: '256m'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: paper
      READ_ONLY_API: "no"
      TIME_ZONE: Asia/Jerusalem
      TWS_ACCEPT_INCOMING: accept
      BYPASS_WARNING: "yes"
      BypassOrderPrecautions: "yes"
      BypassPriceBasedVolatilityRiskWarning: "yes"
      BypassNoOverfillProtectionPrecaution: "yes"
      BypassRedirectOrderWarning: "yes"
      AllowBlindTrading: "yes"
      ENABLE_VNC: "yes"
      ENABLE_VNC_SERVER: "true"
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD}
      OVERRIDE_API_PORT: "4004"
    ports:
      - "4004:4004"
      - "5900:5900"
    depends_on:
      - db

networks:
  default:
    name: selftrading_default
