version: "3.9"

volumes:
  pg_data:
    name: selftrading_pg_data   # ← pinned, won’t change across project/folder renames
  ib_settings:

services:
  db:
    image: postgres:15
    container_name: trading-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-new_self_trading_db}
      APP_USER_PASSWORD: ${DB_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "max_connections=30"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "wal_buffers=8MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "tcp_keepalives_idle=60"
      - "-c"
      - "tcp_keepalives_interval=10"
      - "-c"
      - "tcp_keepalives_count=6"
      - "-c"
      - "log_min_duration_statement=1000"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "log_disconnections=on"
      - "-c"
      - "log_statement=ddl"
      - "-c"
      - "log_checkpoints=on"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "log_temp_files=0"
      - "-c"
      - "log_autovacuum_min_duration=0"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_rotation_size=100MB"
      - "-c"
      - "log_truncate_on_rotation=on"
      - "-c"
      - "restart_after_crash=on"
      - "-c"
      - "max_wal_size=1GB"
      - "-c"
      - "min_wal_size=80MB"
    mem_limit: 512m
    shm_size: 256m
    stop_grace_period: 60s
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/00-init-db.sql:ro
      - ./scripts/10-init-app-user.sh:/docker-entrypoint-initdb.d/10-init-app-user.sh:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s


  db-init-tables:
    image: selftrading-api_gateway
    restart: "no"
    env_file: .env
    environment:
      DATABASE_URL_DOCKER: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DB_ALLOW_AUTO_CREATE_DB: "true"
      DB_ALLOW_AUTO_CREATE_TABLES: "true"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["python", "-m", "backend.database.init_db"]


  import-historical-bars:
    image: selftrading-api_gateway
    restart: "no"
    env_file: .env
    environment:
      DATABASE_URL_DOCKER: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ANALYTICS_SQLITE_PATH: /app/tools/finnhub_downloader/data/daily_bars.sqlite
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      db-init-tables:
        condition: service_completed_successfully
    entrypoint: ["python", "-m", "backend.analytics_importer"]





  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_gateway
    restart: unless-stopped
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: uvicorn backend.api_gateway.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - RUNNING_ENV=analytics
      - DB_ALLOW_AUTO_CREATE_DB=true
      - DB_ALLOW_AUTO_CREATE_TABLES=true
      - ANALYTICS_MODE=true
    depends_on:
      db:
        condition: service_healthy
      db-init-tables:
        condition: service_completed_successfully
      import-historical-bars:
        condition: service_completed_successfully

  client-ui:
    build:
      context: .
      dockerfile: Dockerfile.client-ui-naive
    ports:
      - "8080:80"
    depends_on:
      api_gateway:
        condition: service_started

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    command: python backend/analytics/sim_scheduler.py
    restart: always
    env_file: .env
    environment:
      - RUNNING_ENV=analytics
      - DB_ALLOW_AUTO_CREATE_DB=true
      - DB_ALLOW_AUTO_CREATE_TABLES=true
      - ANALYTICS_MODE=true
      - SIM_PACE_SECONDS=0
      - SIM_STEP_SECONDS=300
    depends_on:
      db:
        condition: service_healthy
      db-init-tables:
        condition: service_completed_successfully
      import-historical-bars:
        condition: service_completed_successfully


  # ib-gateway removed for analytics-only


networks:
  default:
    name: selftrading_default
